# Generated by Django 4.2.5 on 2023-10-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
