# Generated by Django 4.2.5 on 2023-10-02 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_api', '0004_remove_menu_name_remove_menu_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='name',
        ),
        migrations.AddField(
            model_name='dishes',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Dish name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
